version: "3"

services:
  crawl:
    image: dcss
    build:
      context: .
      dockerfile: Dockerfile.webtiles
    restart: always
    ports:
      - 8080:8080
    volumes:
      - crawl:/data

volumes:
  crawl:
